### ISSUE TITLE
show coverage badge in readme

### ISSUE THREAD

**Issue by bgrosse-midokura** [midonet/tssrp6a#38]
now that we have a CI, we should be able to show some coverage percentage badge, like the "ci passing" badge

**Comment by bufistov** [comment]
Are the numbers good enough to show? :)

**Comment by bgrosse-midokura** [comment]
@bufistov 
![image](https://user-images.githubusercontent.com/48123182/110325697-f0f31e00-8017-11eb-9c1e-8e869bf6b152.png)

**Comment by bufistov** [comment]
❤️
