### ISSUE TITLE
What KDF and SRP group is used?

### ISSUE THREAD

**Issue by jbis9051** [midonet/tssrp6a#45]
According to the [1Password's description of SRP](https://blog.1password.com/developers-how-we-use-srp-and-you-can-too/#how-1password-uses-srp) a KDF and SRP group needs to be chosen. 

Which is used in this implementation?

**Comment by bufistov** [comment]
Hi Josh,

This implementation works [with several hashes](https://github.com/midonet/tssrp6a/blob/master/src/parameters.ts#L21).
Feel free to contribute with more!

Any generator can be used but we never tried anything except ["2"](https://github.com/midonet/tssrp6a/blob/master/src/parameters.ts#L101)

There are [several](https://github.com/midonet/tssrp6a/blob/master/src/parameters.ts#L79) big prime numbers to perform "mod" operations. You can trade-off performance/security varying this value.

The default configuration uses:

- hash = SHA512
- g = 2
- N = [2048 bits prime](https://github.com/midonet/tssrp6a/blob/master/src/parameters.ts#L95)

I think we tested all combinations of 'hash' and 'N' parameters.

**Comment by jbis9051** [comment]
Thanks!

**Comment by jbis9051** [comment]
> Feel free to contribute with more!

Is it possible to use a hash function not included in CryptoJS? I think this line would prevent it.

https://github.com/midonet/tssrp6a/blob/master/src/parameters.ts#L48

**Comment by jbis9051** [comment]
> There are several big prime numbers to perform "mod" operations. You can trade-off performance/security varying this value.

256, 512, and 768 aren't listed [in the spec](https://datatracker.ietf.org/doc/html/rfc5054#appendix-A). Where are these primes from?
