### ISSUE TITLE
Make evidence M1 optional in step2 of SRPServerSession

### ISSUE THREAD

**Issue by jbis9051** [midonet/tssrp6a#54]
The shared session key is derived in step2 of SRPServerSession:

https://github.com/midonet/tssrp6a/blob/4c88ce72caa0bcfe38fee881bdc92092c3c4f095/src/session-server.ts#L70

However, step2 requires M1:

https://github.com/midonet/tssrp6a/blob/4c88ce72caa0bcfe38fee881bdc92092c3c4f095/src/session-server.ts#L50
https://github.com/midonet/tssrp6a/blob/4c88ce72caa0bcfe38fee881bdc92092c3c4f095/src/session-server.ts#L66

There maybe times when the user wants to compute the session key, S, without verifying M1. M1 should be optional in step2.

**Comment by bgrosse-midokura** [comment]
Perhaps computeServerSessionKey should be exposed then? I'm referring to being more explicit than "making M1 optional".

**Comment by jbis9051** [comment]
> Perhaps computeServerSessionKey should be exposed then? I'm referring to being more explicit than "making M1 optional".

step2 seems to do more things then just call computeServerSessionKey (including deriving u for computeServerSessionKey), as a user of the library I think I'd prefer the abstraction that step2 provides, just without the M1 requirement.

**Comment by bgrosse-midokura** [comment]
then maybe expose `computeServerEvidence(A: bigint): bigint // returns M2`, and let `step2` be just a call to that plus the equality check.
