### ISSUE TITLE
Can't be used between http requests

### ISSUE THREAD

**Issue by hugbubby** [midonet/tssrp6a#71]
You provide no way to use this library except over websockets. I need to be able to perform this over multiple regular http requests, where I'll have to write down the private key in the meantime etc.

**Comment by jbis9051** [comment]
The library doesn't include anything related to communication between client and server. That is up to you to implement. You can use anything from HTTP to WebSockets to [Avian Carriers](https://en.m.wikipedia.org/wiki/IP_over_Avian_Carriers)

**Comment by hugbubby** [comment]
What I mean is, there's no way to serialize these step objects into a database so that they can be used to verify parts of the process at a later date.

**Comment by bgrosse-midokura** [comment]
You have to add JSON serializer for bignum (just toString)

Take a look at the demo page, it prints out JSON of the steps.

But you are right, we must export the types and so on to make this all more straightforward when the step object isn't keot around.

**Comment by bgrosse-midokura** [comment]
@hugbubby do you want to use the lib with something where the page reloads? The typical use case is with http requests without page reloading.

**Comment by bgrosse-midokura** [comment]
@hugbubby or is it the server part that you want to serialize?

**Comment by bgrosse-midokura** [comment]
@hugbubby the demo is now live here https://midonet.github.io/tssrp6a/demo (it's linked in the readme since yesterday)

**Comment by bufistov** [comment]
Nice work, @bgrosse-midokura !
