### ISSUE TITLE
Shall we reconsider this: This module makes use of Crypto.subtle and therefore only works on HTTPS ?

### ISSUE THREAD

**Issue by bufistov** [midonet/tssrp6a#80]
My understanding is that srp6a provides some security without https. From RFC:

```
SRP ([SRP], [SRP-6]) is an authentication method that allows the use
   of user names and passwords over unencrypted channels without
   revealing the password to an eavesdropper.
```

**Comment by jbis9051** [comment]
The HTTPs restriction is made by browsers. In order to use the built into crypto.subtle methods HTTPs is required or its undefined. 

Users can add a polyfill if they want to use the library on HTTP. However, they really shouldn't. While it doesn't impact the security of the library per se, HTTPS should always be used.

**Comment by bgrosse-midokura** [comment]
@bufistov https://github.com/midonet/tssrp6a#recommendations

Using SRP over HTTP gives a false sense of security, with HTTP the password could be intercepted as easily as with regular forms that submit the password.

What I do think we should consider, is testing with a custom hash function. That would technically allow to run over HTTP too, but the point would be to test the ability to use an alternative crypto, for whatever reason.

**Comment by bufistov** [comment]
I do agree that using SRP6a via HTTP does not make too much sense. Still supporting this would make library more flexible.
What if I don't want to use HTTPS in my integration tests, for example?

**Comment by jbis9051** [comment]
> Locally-delivered resources such as those with http://127.0.0.1 URLs, http://localhost and  http://*.localhost URLs (e.g. http://dev.whatever.localhost/), and file:// URLs are also considered to have been delivered securely.

You can also disable this requirement in the browser config.

**Comment by bufistov** [comment]
Ok, closing  the issue :)
