### ISSUE TITLE
Add project description on GitHub

### ISSUE THREAD

**Issue by jbis9051** [midonet/tssrp6a#85]
Can we add a description here? Thanks :)

<img width="228" alt="Screen Shot 2021-08-19 at 9 10 10 PM" src="https://user-images.githubusercontent.com/32957090/130163353-248f3e96-f6a2-48bf-a33c-506a9afe269c.png">

**Comment by bufistov** [comment]
I tried to do it, but I think I miss permissions. @bgrosse-midokura  ?

**Comment by bgrosse-midokura** [comment]
@bufistov added :)

**Comment by bufistov** [comment]
Done!

**Comment by jbis9051** [comment]
Thanks!
